import type { Dnd5eCombatEvent } from '../rulesets/dnd5e/headlessCombatEngine'
import { DND5E_DAMAGE_TYPE_LABELS } from '../rulesets/dnd5e/damageTypes'
import { dnd5eConditionLabel } from '../rulesets/dnd5e/conditions'
const abilities = {str:'力量',dex:'敏捷',con:'体质',int:'智力',wis:'感知',cha:'魅力'}

/** Describe only facts carried by authoritative events; do not infer a missing trigger. */
export function additionalCombatLogDetails(event: Dnd5eCombatEvent, name: (id:string)=>string, hideDice = false, publicRollerIds: ReadonlySet<string> = new Set()): string[] {
  const targets = (ids: readonly string[]) => ids.map(name).join('、') || '无'
  const outcome = (success: boolean) => success ? '成功' : '失败'
  const dice = (text: string) => hideDice ? '' : `｜${text}`
  switch(event.type) {
    case 'halfling-lucky-rerolled': return [`${name(event.actorId)}｜幸运触发：第 ${event.dieIndex + 1} 颗骰子掷出 1，重新投掷${hideDice ? '' : `｜1 → ${event.reroll}`}`]
    case 'savage-attacks-applied': return [`${name(event.actorId)} → ${name(event.targetId)}｜凶蛮攻击：重击追加一颗武器伤害骰${hideDice ? '' : `｜结果 ${event.roll}`}${event.damageType ? `｜${DND5E_DAMAGE_TYPE_LABELS[event.damageType]}伤害` : ''}`]
    case 'relentless-endurance-triggered': return [`${name(event.actorId)}｜坚韧不屈：生命值降至 0 时触发，改为保留 1 点生命值`]
    case 'action-surge-granted': return [`${name(event.actorId)}｜动作如潮：本回合获得一个额外动作`]
    case 'condition-attempted': return event.prevented ? [`${name(event.actorId)} → ${name(event.targetId)}｜尝试施加${dnd5eConditionLabel(event.condition)}，被防护或免疫阻止`] : []
    case 'teleportation-blocked-by-area': return [`${name(event.actorId)}｜${event.spellId}的传送被所在区域阻止，未发生位移`]
    case 'creature-revived': return [`${name(event.actorId)} → ${name(event.targetId)}｜复活完成，恢复 ${event.hitPoints} 点生命值${event.penalty ? `｜复活惩罚 ${event.penalty}` : ''}${event.casterStrained ? '｜施法者承受复活负担' : ''}`]
    case 'hit-point-maximum-reduced': return [`${name(event.sourceId)} → ${name(event.targetId)}｜生命值上限降低 ${event.appliedAmount}：${event.maximumBefore} → ${event.maximumAfter}｜${event.recovery === 'long-rest' ? '长休后恢复' : '需高等复原术或其他恢复魔法'}`]
    case 'ability-score-reduced': return [`${name(event.sourceId)} → ${name(event.targetId)}｜${abilities[event.ability]}降低 ${event.amount}：${event.scoreBefore} → ${event.scoreAfter}`]
    case 'armor-corroded': return [`${name(event.sourceId)} → ${name(event.targetId)}｜护甲腐蚀，护甲等级降至 ${event.armorClassAfter}${event.destroyed ? '｜护甲已损毁' : ''}`]
    case 'divine-intervention-resolved': return [`${name(event.actorId)}｜神圣干预${event.automatic ? '（自动成功）' : hideDice ? '' : `｜百分骰 ${event.d100 ?? '未记录'}`}｜${event.success ? '回应成功' : '未获得回应'}${event.cooldownDays ? `｜${event.cooldownDays} 天后可再次使用` : ''}`]
    case 'plugin-feature-passive-effect-applied': return [`${name(event.actorId)} → ${name(event.targetId)}｜${event.featureName}：受到伤害时减免 ${event.amount} 点伤害`]
    case 'warding-bond-damage-transferred': return [`${name(event.targetId)} → ${name(event.sourceActorId)}｜守护之链：受保护者受到伤害，施法者分担 ${event.amount} 点伤害`]
    case 'declarative-death-prevention-applied': return [`${name(event.actorId)}｜${event.featureId}防止死亡，生命值调整为 ${event.hitPointsAfter}`]
    case 'declarative-concentration-check-prevented': return [`${name(event.actorId)}｜${event.featureId}：本次受到 ${event.damage} 点伤害无需专注检定，维持${event.spellId}`]
    case 'declarative-damage-reflected': return [`${name(event.actorId)} → ${name(event.sourceId)}｜${event.featureId}：将 ${event.amount} 点${DND5E_DAMAGE_TYPE_LABELS[event.damageType]}伤害反射给来源`]
    case 'damage-resistance-gained': return [`${name(event.actorId)}｜元素亲和：获得${DND5E_DAMAGE_TYPE_LABELS[event.damageType]}伤害抗性，持续 ${event.rounds} 回合`]
    case 'undead-turned': case 'unholy-turned': return [`${name(event.actorId)} → ${name(event.targetId)}｜驱散生效，持续 ${event.rounds} 回合`]
    case 'undead-destroyed': return [`${name(event.actorId)} → ${name(event.targetId)}｜摧毁亡灵：目标满足驱散后的摧毁条件，立即被消灭`]
    case 'confused-turn-behavior-resolved': return [`${name(event.actorId)}｜困惑术回合判定${hideDice ? '' : `：d10 ${event.roll}`}｜${{'random-movement-no-action':'随机移动且不能执行动作','no-movement-or-action':'不能移动或执行动作','random-melee-attack':'随机选择目标进行近战攻击',normal:'本回合正常行动'}[event.mode]}${event.forcedTargetId ? `｜目标 ${name(event.forcedTargetId)}` : ''}`]
    case 'post-d20-adjustment-applied': return [`${name(event.actorId)} → ${name(event.targetId)}｜${event.featureId}：在检定后${event.direction === 'add' ? '增加' : '减少'}结果${hideDice ? '' : `｜特性骰 ${event.roll}，调整 ${event.amount}`}`]
    case 'opposed-ability-check-resolved': {
      const source = hideDice && !publicRollerIds.has(event.actorId) ? '暗骰' : `${event.sourceD20} ${event.sourceModifier >= 0 ? '+' : ''}${event.sourceModifier} = ${event.sourceTotal}`
      const target = hideDice && !publicRollerIds.has(event.targetId) ? '暗骰' : `${event.targetD20} ${event.targetModifier >= 0 ? '+' : ''}${event.targetModifier} = ${event.targetTotal}`
      return [`${name(event.actorId)} → ${name(event.targetId)}｜${abilities[event.sourceAbility]}对抗 ${source}，对抗${abilities[event.targetAbility]} ${target}｜${event.success ? '成功' : '失败'}`]
    }
    case 'turn-started': return [`${name(event.actorId)}｜第 ${event.round} 回合开始`]
    case 'spell-authority-record-established': return [`${name(event.actorId)} → ${name(event.targetId)}｜${event.activityId}：建立持续法术记录｜创建时刻 ${event.createdWorldMinute} 分钟${event.maturesAtWorldMinute == null ? '' : `｜成熟时刻 ${event.maturesAtWorldMinute} 分钟`}`]
    case 'clone-soul-transferred': return [`${name(event.actorId)}｜克隆体接收灵魂｜生命值上限 ${event.maximumHitPoints}`]
    case 'item-area-triggered': return [`${name(event.actorId)}｜触发${{'ball-bearings':'滚珠','caltrops':'铁蒺藜','hunting-trap':'捕猎陷阱'}[event.areaKind]}｜检定${outcome(event.success)}`]
    case 'scene-interaction-outcome-resolved': return [`${name(event.actorId)}｜场景交互完成 ${event.stepCount} 步`]
    case 'attack-retarget-save-resolved': return [`${name(event.actorId)}｜${event.featureId}：攻击转移豁免${dice(`20 面骰 ${event.d20} + ${event.total - event.d20} = ${event.total} 对抗难度 ${event.dc}`)}｜${outcome(event.success)}｜原目标 ${name(event.originalTargetId)} → 最终目标 ${name(event.finalTargetId)}`]
    case 'mounted-attack-redirected': return [`${name(event.actorId)}｜骑乘保护：对 ${name(event.mountId)} 的攻击转向骑手 ${name(event.riderId)}`]
    case 'monster-relentless-triggered': return [`${name(event.actorId)}｜坚韧触发：本次伤害 ${event.damage} 不超过 ${event.maximumDamage}，保留 1 点生命值`]
    case 'dragonborn-breath-resolved': return [`${name(event.actorId)}｜龙裔吐息｜目标 ${targets(event.targetIds)}｜基础伤害 ${event.damage}${dice(`豁免难度 ${event.dc}`)}`]
    case 'command-turn-resolved': return [`${name(event.actorId)}｜执行命令：${{'approach':'靠近','drop':'放下','flee':'逃离','grovel':'趴下','halt':'停下','other':'其他命令'}[event.mode]}｜放下物品 ${targets(event.droppedItemIds)}${event.endedTurn ? '｜回合结束' : ''}`]
    case 'creatures-sensed': return [`${name(event.actorId)}｜感知到生物：${targets(event.targetIds)}`]
    case 'creature-types-sensed': return [`${name(event.actorId)}｜感知生物类型：${event.creatureTypes.join('、')}｜持续 ${event.durationRounds} 回合`]
    case 'communication-opened': return [`${name(event.actorId)} → ${name(event.targetId)}｜魔法低语已送达${event.allowsImmediateReply ? '，目标可立即回复' : ''}`]
    case 'draconic-presence-save-required': return [`${name(event.targetId)}｜受到 ${name(event.sourceId)} 的龙威${event.mode === 'awe' ? '震慑' : '恐惧'}影响，等待豁免${dice(`难度 ${event.dc}`)}`]
    case 'undead-fortitude-save-required': return [`${name(event.targetId)}｜亡灵坚韧：受到 ${event.damage} 点伤害后等待豁免${dice(`难度 ${event.dc}`)}`]
    case 'monster-on-hit-save-required': return [`${name(event.sourceId)} → ${name(event.targetId)}｜攻击命中触发${event.condition === 'disease' ? '疾病' : dnd5eConditionLabel(event.condition)}判定，等待${abilities[event.ability]}豁免${dice(`难度 ${event.dc}`)}`]
    case 'monster-triggered-bonus-action-available': return [`${name(event.actorId)}｜命中 ${name(event.targetId)} 后，可使用附赠动作：${event.actionId}`]
    case 'exhaustion-gained': return [`${name(event.actorId)}｜力竭增加，当前 ${event.level} 级`]
    case 'spell-negated-by-limited-magic-immunity': return [`${name(event.actorId)} → ${name(event.targetId)}｜有限魔法免疫阻止 ${event.spellLevel} 环${event.spellId}，法术未生效`]
    case 'monster-regenerated': return [`${name(event.actorId)}｜再生恢复 ${event.amount} 点生命值｜当前 ${event.hpAfter}`]
    case 'monster-regeneration-suppressed': return [`${name(event.actorId)}｜受到${event.damageTypes.map(type => DND5E_DAMAGE_TYPE_LABELS[type]).join('、')}伤害，阻止再生${event.died ? '｜死亡' : ''}`]
    case 'monster-berserk-resolved': return [`${name(event.actorId)}｜狂暴判定${dice(`骰值 ${event.roll}`)}｜${event.berserk ? '进入狂暴' : '未进入狂暴'}`]
    case 'monster-berserk-ended': return [`${name(event.actorId)}｜生命值完全恢复，狂暴结束`]
    case 'monster-damage-aversion-triggered': return [`${name(event.actorId)}｜受到${DND5E_DAMAGE_TYPE_LABELS[event.damageType]}伤害，触发伤害畏惧`]
    case 'monster-damage-aversion-ended': return [`${name(event.actorId)}｜伤害畏惧结束`]
    case 'monster-damage-absorbed': return [`${name(event.actorId)}｜吸收 ${event.amount} 点${DND5E_DAMAGE_TYPE_LABELS[event.damageType]}伤害，恢复 ${event.healing} 点生命值`]
    case 'monster-hydra-head-severed': return [`${name(event.actorId)}｜本回合累计受到 ${event.damageTakenThisTurn} 点伤害，头颅被斩断｜剩余 ${event.headCount} 个头颅`]
    case 'monster-hydra-heads-regrown': return [`${name(event.actorId)}｜再生 ${event.headsRegrown} 个头颅，当前 ${event.headCount} 个｜恢复 ${event.healing} 点生命值，当前 ${event.hpAfter}`]
    case 'monster-hydra-regrowth-suppressed': return [`${name(event.actorId)}｜火焰伤害阻止 ${event.headsLost} 个断头再生｜剩余 ${event.headCount} 个头颅`]
    case 'monster-swallow-internal-damage-tracked': return [`${name(event.actorId)}｜来自腹中 ${name(event.sourceId)} 的伤害本回合累计 ${event.damageTakenThisTurn}｜吐出检定触发阈值 ${event.threshold}`]
    case 'monster-swallow-regurgitation-resolved': return [`${name(event.actorId)}｜腹内受到 ${event.damageTaken} 点伤害，吐出豁免${dice(`难度 ${event.dc}`)}｜${outcome(event.success)}｜吐出 ${targets(event.ejectedTargetIds)}，放置于 ${event.placementWithinFeet} 尺内`]
    case 'monster-swallow-corpse-containment-started': return [`${name(event.targetId)}｜被困于 ${name(event.sourceId)} 尸体内，脱离需消耗 ${event.movementCostFeet} 尺移动`]
    case 'monster-swallow-corpse-escaped': return [`${name(event.targetId)}｜消耗 ${event.movementCostFeet} 尺移动脱离 ${name(event.sourceId)} 尸体，倒地`]
    case 'monster-recharge-resolved': return [`${name(event.actorId)}｜${event.actionId}充能${dice(`骰值 ${event.roll}`)}｜${event.ready ? '恢复可用' : '尚未恢复'}`]
    case 'monster-mechanic-triggered': return [`${name(event.actorId)}｜${event.mechanicName}触发｜数值 ${event.amount}｜生命值 ${event.hpAfter}`]
    case 'monster-mechanic-trigger-pending': return [`${name(event.snapshot.mechanicOwnerId)}｜${event.snapshot.mechanicId}等待结算｜触发：${event.snapshot.event}｜关联 ${name(event.snapshot.subjectId)}`]
    case 'monster-death-area-effect-pending': return [`${name(event.snapshot.sourceId)}｜死亡区域效果待结算｜目标 ${targets(event.snapshot.targetIds)}`]
    case 'monster-death-area-effect-resolved': return [`${name(event.sourceId)}｜死亡区域效果生效｜目标 ${targets(event.targetIds)}｜基础伤害 ${event.damage}`]
    case 'monster-attack-trait-damage-applied': return [`${name(event.actorId)} → ${name(event.targetId)}｜${event.traitName}触发，追加 ${event.amount} 点伤害`]
    case 'monster-mechanic-v2-triggered': return [`${name(event.actorId)}｜${event.mechanicName}｜触发：${event.trigger}`, ...event.outcomes.map(result => `${name(result.targetId)}｜${{'healing':'治疗','temporary-hit-points':'临时生命值','damage':'伤害','damage-replacement':'伤害替换','standard-condition':'施加状态','tactical-status':'战术状态','remove-standard-condition':'移除状态','roll-modifier':'检定修正','attack':'攻击','action-grant':'授予动作','equipment-modifier':'装备修正'}[result.kind]}${result.condition ? `：${dnd5eConditionLabel(result.condition)}` : ''}${result.amount == null ? '' : ` ${result.amount}`}${result.applied === false ? '｜未生效' : ''}`)]
    case 'monster-legendary-actions-restored': return [`${name(event.actorId)}｜传奇动作恢复至 ${event.points} 点`]
    case 'monster-legendary-action-used': return [`${name(event.actorId)}｜使用传奇动作 ${event.actionId}｜消耗 ${event.cost}，剩余 ${event.remaining} 点`]
    case 'monster-special-action-resolved': return [`${name(event.actorId)}${event.targetId ? ` → ${name(event.targetId)}` : ''}｜${event.actionId}特殊动作结算${event.success == null ? '' : `｜${outcome(event.success)}`}${event.damage == null ? '' : `｜伤害 ${event.damage}`}${event.healing == null ? '' : `｜治疗 ${event.healing}`}${event.total == null ? '' : dice(`检定合计 ${event.total}`)}`]
    case 'monster-summon-resolved': return [`${name(event.actorId)}｜召唤 ${event.count} 个${event.monsterId}｜${event.timing === 'immediate' ? '立即出现' : '施法者下回合开始出现'}｜持续 ${event.durationRounds} 回合${event.concentration ? '｜需要专注' : ''}${event.concentrationEndsOnAppearance ? '｜出现后结束专注' : ''}`]
    case 'monster-legendary-detect-resolved': return [`${name(event.actorId)}｜传奇侦测${dice(`20 面骰 ${event.d20} + ${event.modifier} = ${event.total}`)}`]
    case 'monster-legendary-wing-attack-resolved': return [`${name(event.actorId)}｜振翅攻击｜目标 ${targets(event.targetIds)}｜基础伤害 ${event.damage}｜获得 ${event.movementGranted} 尺移动`]
    case 'monster-adjudicated-action-resolved': return [`${name(event.actorId)}｜${event.actionId}裁定完成，应用 ${event.effectCount} 项效果`]
    case 'monster-spell-cast': return [`${name(event.actorId)}｜施放 ${event.spellId}（${event.slotLevel} 环）${event.remainingSlots == null ? '' : `｜剩余法术位 ${event.remainingSlots}`}`]
    case 'monster-core-spell-resolved': return [`${name(event.actorId)}｜${event.spellId}（${event.slotLevel} 环）结算｜目标 ${targets(event.targetIds)}`]
    case 'monster-area-action-resolved': return [`${name(event.actorId)}｜${event.actionId}区域效果｜目标 ${targets(event.targetIds)}｜基础伤害 ${event.damage}`]
    case 'monster-multiattack-composite-resolved': return [`${name(event.actorId)}｜多重攻击｜完成 ${event.resolvedActionIds.join('、') || '无'}｜跳过 ${event.skippedActionIds.join('、') || '无'}`]
    case 'monster-multiattack-random-repeat-resolved': return [`${name(event.actorId)}｜随机多重攻击${dice(`骰值 ${event.roll}`)}｜攻击 ${event.attackCount} 次`]
    case 'monster-multiattack-occurrence-skipped': return [`${name(event.actorId)}｜第 ${event.occurrenceIndex + 1} 次${event.childActionId}：目标不符合条件，跳过`]
    case 'monster-shapechanged': return [`${name(event.actorId)}｜${event.forced ? '强制' : ''}变形：${event.fromStatBlockId} → ${event.toStatBlockId}`]
    case 'monster-lair-action-used': return [`${name(event.actorId)}｜第 ${event.round} 回合使用巢穴动作 ${event.actionId}｜应用 ${event.effectCount} 项效果`]
    case 'declarative-subclass-ability-resolved': return [`${name(event.actorId)}｜${event.abilityId}生效｜触发：${event.trigger}｜目标 ${targets(event.targetIds)}`]
    case 'declarative-subclass-trigger-rejected': return [`${name(event.actorId)}｜${event.abilityId}未触发｜尝试：${event.trigger}｜原因：${event.reason}`]
    case 'combat-maneuver-resolved': return [`${name(event.actorId)}${event.targetId ? ` → ${name(event.targetId)}` : ''}｜${event.featureId}战技${!hideDice || publicRollerIds.has(event.actorId) ? `｜卓越骰 ${event.superiorityDie}` : ''}${event.saveSucceeded == null ? '' : `｜豁免${outcome(event.saveSucceeded)}`}${event.saveDc == null || hideDice && (!event.targetId || !publicRollerIds.has(event.targetId)) ? '' : `｜难度 ${event.saveDc}`}${event.value == null ? '' : `｜效果数值 ${event.value}`}`]
    case 'combat-maneuver-weapon-dropped': return [`${name(event.actorId)} → ${name(event.targetId)}｜缴械生效，放下 ${event.weaponId}`]
    case 'active-effect-periodic-damage-triggered': return [`${name(event.targetId)}｜${event.definitionId}持续伤害触发｜受到 ${event.amount} 点${event.damageType ? DND5E_DAMAGE_TYPE_LABELS[event.damageType] : ''}伤害`]
    case 'active-effect-manually-removed': return [`${name(event.actorId)} → ${name(event.targetId)}｜主动解除 ${event.label}｜${outcome(event.success)}`]
    case 'monster-turn-start-gaze-declined': return [`${name(event.sourceId)} → ${name(event.targetId)}｜本次不使用凝视`]
    case 'monster-turn-start-gaze-averted': return [`${name(event.targetId)}｜移开视线，避免 ${name(event.sourceId)} 的凝视`]
    case 'monster-turn-start-gaze-save-resolved': return [`${name(event.targetId)}｜${event.featureName ?? (event.effectKind === 'gaze' ? '凝视' : '灵气')}${abilities[event.ability]}豁免${dice(`${event.total} 对抗难度 ${event.dc}`)}｜${outcome(event.success)}${event.immediatelyPetrified ? '｜立即石化' : ''}`]
    case 'monster-reckless-activated': return [`${name(event.actorId)}｜鲁莽攻击生效`]
    case 'monster-parry-used': return [`${name(event.actorId)}｜对 ${name(event.attackerId)} 的攻击使用招架${dice(`护甲等级 +${event.armorClassBonus}，当前 ${event.armorClass}`)}`]
    case 'monster-reactive-refreshed': return [`${name(event.actorId)}｜新回合恢复反应`]
    case 'activity-resolved': return [`${name(event.actorId)}｜${event.sourceId}规则结算完成｜目标 ${targets(event.targetIds)}${event.castLevel == null ? '' : `｜${event.castLevel} 环`}`]
    case 'post-spell-random-table-choice-resolved': return [`${name(event.actorId)}｜${event.featureId}：选择第 ${event.selectedIndex + 1} 个随机结果${dice(`候选 ${event.rolls.join('、')}，采用 ${event.selectedRoll}`)}`]
    case 'declarative-ward-pool-changed': return [`${name(event.actorId)}｜${event.featureId}：护盾池${{'created':'建立','restored':'恢复','absorbed':'吸收伤害','projected':'保护他人'}[event.reason]}｜当前 ${event.current}/${event.max}`]
    case 'damage-mitigation-interrupt-applied': return [`${name(event.actorId)} → ${name(event.targetId)}｜${event.featureId}：以${event.mode === 'resistance' ? '抗性' : '护盾池'}减免 ${event.prevented} 点伤害`]
    case 'spell-damage-max-die-bonus-applied': return [`${name(event.actorId)}｜${event.featureId}为${event.spellId}追加 ${event.amount} 点伤害${dice(`${event.dieSides} 面骰：${event.rolls.join('、')}`)}`]
    case 'hellish-rebuke-resolved': return [`${name(event.actorId)} → ${name(event.targetId)}｜受到伤害后施放 ${event.slotLevel} 环炼狱叱喝｜豁免${outcome(event.success)}${!hideDice || publicRollerIds.has(event.targetId) ? `｜${event.saveTotal} 对抗难度 ${event.dc}` : ''}｜伤害 ${event.damage}`]
    case 'adjudicated-spell-resolved': return [`${name(event.actorId)}｜${event.spellName}（${event.slotLevel} 环）裁定完成｜应用 ${event.effectCount} 项效果`]
    case 'metamagic-applied': return [`${name(event.actorId)}｜${event.spellId}应用超魔法：${event.kind}${event.targetId ? `｜目标 ${name(event.targetId)}` : ''}`]
    case 'linked-equipment-recalled': return [`${name(event.actorId)}｜召回绑定装备 ${event.weaponId}`]
    case 'declarative-spell-defeat-healing-applied': return [`${name(event.actorId)}｜${event.spellId}击败 ${targets(event.defeatedTargetIds)} 后触发${event.featureId}｜治疗上限 ${event.amount}，实际恢复 ${event.healed}`]
    case 'object-action-taken': return [`${name(event.actorId)}｜${event.action === 'use-object' ? '使用物品动作' : '物品交互'}完成`]
    case 'hide-resolved': return [`${name(event.actorId)}｜躲藏检定${dice(`20 面骰 ${event.d20} + ${event.total - event.d20} = ${event.total}`)}`]
    case 'help-granted': return [`${name(event.actorId)} → ${name(event.targetId)}｜协助${event.helpKind === 'attack' ? '攻击' : '属性检定'}，提供优势`]
    case 'ready-declared': return [`${name(event.actorId)}｜预备动作已声明｜触发条件：${event.trigger}`]
    case 'readied-action-triggered': return [`${name(event.actorId)}｜预备动作触发｜满足条件：${event.trigger}`]
    case 'monster-on-hit-contest-resolved': return [`${name(event.actorId)} → ${name(event.targetId)}｜命中后对抗：${abilities[event.sourceAbility]} ${!hideDice || publicRollerIds.has(event.actorId) ? event.sourceTotal : '暗骰'} 对抗${abilities[event.targetAbility]} ${!hideDice || publicRollerIds.has(event.targetId) ? event.targetTotal : '暗骰'}｜主动方${outcome(event.sourceWins)}`]
    case 'relentless-rage-save-required': return [`${name(event.targetId)}｜坚韧狂暴：生命值降至 0，等待体质豁免${dice(`难度 ${event.dc}`)}`]
    case 'creature-stabilized': return [`${name(event.actorId)} → ${name(event.targetId)}｜伤势稳定，停止死亡豁免`]
    default: return []
  }
}
