import {
  appendSharedPlayerActionRequest,
  clearSharedEventBacklog,
  clearSharedResource,
  deleteSharedImage,
  getSharedImage,
  getSharedResourceRevisionWatermark,
  loadSharedResource,
  loadDmUndoHistory,
  mutateSharedCombatInterrupt,
  mutateSharedRoomResource,
  publishSharedEvent,
  putSharedImage,
  recoverDmCombatToTransaction,
  sampleSharedServerClock,
  saveSharedResource,
  saveSharedResourcesAtomically,
  saveSharedResourceWithResult,
  submitSharedPlayerCharacterCommand,
  subscribeSharedEvent,
  subscribeSharedResourceInvalidation,
  undoDmTransaction,
} from '../../lib/sharedApi'
import type { SharedRoomGatewayPort } from '../../ports/sharedRoomGateway'

/** Browser HTTP/SSE adapter. Transport details stay outside Presentation. */
export const sharedApiRoomGateway: SharedRoomGatewayPort = {
  getRevisionWatermark: getSharedResourceRevisionWatermark,
  loadResource: loadSharedResource,
  saveResource: saveSharedResource,
  saveResourceWithResult: saveSharedResourceWithResult,
  saveResourcesAtomically: saveSharedResourcesAtomically,
  appendPlayerActionRequest: appendSharedPlayerActionRequest,
  submitPlayerCharacterCommand: submitSharedPlayerCharacterCommand,
  loadDmUndoHistory,
  undoDmTransaction,
  recoverDmCombatToTransaction,
  publishEvent: publishSharedEvent,
  clearEventBacklog: clearSharedEventBacklog,
  clearResource: clearSharedResource,
  mutateResource: mutateSharedRoomResource,
  putImage: putSharedImage,
  getImage: getSharedImage,
  deleteImage: deleteSharedImage,
  sampleServerClock: sampleSharedServerClock,
  mutateCombatInterrupt: mutateSharedCombatInterrupt,
  subscribeEvent: subscribeSharedEvent,
  subscribeResourceInvalidation: subscribeSharedResourceInvalidation,
}
