import { useMemo, useState } from 'react'
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import type { MobileInterruptRegistryV1, MobileInterruptView } from '../../../../packages/mobile-protocol/src'
import { colors } from '../theme'
import { resolveMobileInterruptDescriptor, safeInterruptOptions } from '../services/interruptRegistry'

interface Choice { id: string; label: string; description?: string }

export function InterruptBanner({ interrupt, registry, activeCharacterId, onAnswer }: { interrupt: MobileInterruptView; registry: MobileInterruptRegistryV1; activeCharacterId: string | null; onAnswer: (response: Record<string, unknown>) => Promise<void> }) {
  const [open, setOpen] = useState(false)
  const [selectedDice, setSelectedDice] = useState<string[]>([])
  const descriptor = resolveMobileInterruptDescriptor(registry, interrupt)
  const payload = interrupt.payload
  const title = String(payload.featureName ?? payload.label ?? payload.title ?? descriptor.title ?? interrupt.kind)
  const choices = useMemo<Choice[]>(() => safeInterruptOptions(interrupt, descriptor).map((choice) => ({
    ...choice,
    label: descriptor.mode === 'target-list' ? `改攻 ${choice.label}` : choice.label,
  })), [descriptor, interrupt])
  if (interrupt.status !== 'open' && interrupt.status !== 'pending' && interrupt.status !== 'rolling') return null
  return <>
    <Pressable style={styles.banner} onPress={() => setOpen(true)}><View style={styles.pulse} /><View style={{ flex: 1 }}><Text style={styles.eyebrow}>等待你的决定</Text><Text numberOfLines={1} style={styles.title}>{title}</Text><Text style={styles.meta}>{interrupt.expiresAt ? `剩余 ${Math.max(0, Math.ceil((interrupt.expiresAt - Date.now()) / 1000))} 秒` : '点击处理反应窗口'}</Text></View><Text style={styles.open}>处理</Text></Pressable>
    <Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><View style={styles.backdrop}><View style={styles.dialog}><View style={styles.head}><View><Text style={styles.dialogEyebrow}>Headless Interrupt</Text><Text style={styles.dialogTitle}>{title}</Text></View><Pressable onPress={() => setOpen(false)}><Text style={styles.close}>×</Text></Pressable></View><Text style={styles.description}>{interruptDescription(interrupt)}</Text>
      <ScrollView style={styles.scroll} contentContainerStyle={styles.options}>
        {descriptor.mode === 'boolean' && descriptor.responseKey && <View style={styles.two}><ChoiceButton label={descriptor.declineLabel || '不使用'} onPress={() => void answer({ [descriptor.responseKey!]: false })} /><ChoiceButton label={descriptor.useLabel || '使用'} primary onPress={() => void answer({ [descriptor.responseKey!]: true })} /></View>}
        {!!choices.length && choices.map((choice) => <ChoiceButton key={choice.id} label={choice.label} detail={choice.description} onPress={() => void answer({ [descriptor.optionIdKey || 'optionId']: choice.id })} />)}
        {descriptor.mode === 'target-list' && <ChoiceButton label="保留反应" onPress={() => void answer({})} />}
        {descriptor.mode === 'empowered-spell' && <EmpoweredSpellOptions payload={payload} selected={selectedDice} onChange={setSelectedDice} onSubmit={(rerollKeys) => void answer({ rerollKeys })} />}
        {descriptor.mode === 'roll-confirmation' && <RollConfirmationOptions interrupt={interrupt} activeCharacterId={activeCharacterId} onSubmit={(response) => void answer(response)} />}
        {descriptor.mode === 'host-only' && <Text style={styles.unsupported}>该窗口不属于玩家决定，Host 会继续保留权威事务。</Text>}
      </ScrollView>
    </View></View></Modal>
  </>

  async function answer(response: Record<string, unknown>) { await onAnswer(response); setOpen(false) }
}

function EmpoweredSpellOptions({ payload, selected, onChange, onSubmit }: { payload: Record<string, unknown>; selected: string[]; onChange: (value: string[]) => void; onSubmit: (value: string[]) => void }) {
  const maximum = Number(payload.maximumDice) || 1
  const groups = Array.isArray(payload.groups) ? payload.groups.filter(isDiceGroup) : []
  return <View style={styles.optionGroup}><Text style={styles.hint}>选择至多 {maximum} 枚伤害骰重掷，新结果必须采用。</Text>{groups.map((group) => <View key={group.key} style={styles.diceGroup}><Text style={styles.choiceLabel}>{group.label} · d{group.sides}</Text><View style={styles.diceRow}>{group.rolls.map((value, index) => { const key = `${group.key}:${index}`; const active = selected.includes(key); return <Pressable key={key} style={[styles.die, active && styles.dieActive]} onPress={() => onChange(active ? selected.filter((entry) => entry !== key) : selected.length < maximum ? [...selected, key] : selected)}><Text style={styles.dieText}>{value}</Text></Pressable> })}</View></View>)}<View style={styles.two}><ChoiceButton label="不使用" onPress={() => onSubmit([])} /><ChoiceButton label="重掷所选骰子" primary disabled={!selected.length} onPress={() => onSubmit(selected)} /></View></View>
}

function RollConfirmationOptions({ interrupt, activeCharacterId, onSubmit }: { interrupt: MobileInterruptView; activeCharacterId: string | null; onSubmit: (response: Record<string, unknown>) => void }) {
  const payload = interrupt.payload
  const [replacementValue, setReplacementValue] = useState('')
  const eligible = Array.isArray(payload.eligibleModifiers) ? payload.eligibleModifiers.filter(isModifier) : []
  const ownCharacterIds = new Set([activeCharacterId].filter(Boolean))
  const own = eligible.filter((entry) => ownCharacterIds.has(entry.characterId))
  if (!own.length) return <Text style={styles.hint}>你没有可用的投骰修改特性，Host 会自动继续结算。</Text>
  const ownContribution = interrupt.contributions?.find((entry) => ownCharacterIds.has(entry.characterId))
  const rollOptions = payload.rollOptions && typeof payload.rollOptions === 'object' ? payload.rollOptions as { contributionId?: string; values?: unknown[] } : null
  if (ownContribution?.kind === 'choice-reroll' && rollOptions?.contributionId === ownContribution.id && Array.isArray(rollOptions.values)) return <View style={styles.optionGroup}><Text style={styles.hint}>Host 已完成额外投骰，请选择最终采用的结果。</Text><View style={styles.diceRow}>{rollOptions.values.map((value, index) => <ChoiceButton key={`${index}:${String(value)}`} label={`${index === 0 ? '原始结果' : `新骰 ${index}`}：${String(value)}`} onPress={() => onSubmit({ operation: 'contribute', contribution: { featureId: ownContribution.featureId, featureLabel: ownContribution.featureLabel, choiceDecision: 'use', selectedIndex: index } })} />)}</View></View>
  return <View style={styles.optionGroup}><View style={styles.roll}><Text style={styles.rollLabel}>{String(payload.label || '当前 d20')}</Text><Text style={styles.rollValue}>{Number(payload.originalValue) || '—'}</Text></View>{own.map((feature) => <View key={feature.featureId} style={styles.modifier}>{feature.modifierKind !== 'adjust-d20' && feature.modifierKind !== 'choice-reroll' && <TextInput value={replacementValue} onChangeText={setReplacementValue} keyboardType="number-pad" placeholder="输入 1-20 替换点数" placeholderTextColor={colors.muted} style={styles.replacement} />}<ChoiceButton label={feature.featureLabel} detail={feature.modifierKind === 'choice-reroll' ? `额外投掷 ${feature.additionalDice || 1} 枚 d20` : feature.modifierKind === 'adjust-d20' ? `投掷 d${feature.dieSides || '?'} 修正` : '替换本次 d20'} disabled={feature.modifierKind !== 'adjust-d20' && feature.modifierKind !== 'choice-reroll' && !(Number(replacementValue) >= 1 && Number(replacementValue) <= 20)} onPress={() => onSubmit({ operation: 'contribute', contribution: { featureId: feature.featureId, featureLabel: feature.featureLabel, ...(feature.modifierKind === 'choice-reroll' ? { choiceDecision: 'use' } : feature.modifierKind === 'adjust-d20' ? { direction: feature.direction } : { replacementValue: Number(replacementValue) }) } })} /></View>)}<ChoiceButton label="不使用投骰修改" onPress={() => onSubmit({ operation: 'contribute', contribution: { featureId: '', featureLabel: '', decline: true } })} /></View>
}

function ChoiceButton({ label, detail, primary, disabled, onPress }: { label: string; detail?: string; primary?: boolean; disabled?: boolean; onPress: () => void }) { return <Pressable disabled={disabled} style={[styles.choice, primary && styles.choicePrimary, disabled && styles.disabled]} onPress={onPress}><Text style={styles.choiceLabel}>{label}</Text>{!!detail && <Text style={styles.choiceDetail}>{detail}</Text>}</Pressable> }
function isDiceGroup(value: unknown): value is { key: string; label: string; sides: number; rolls: number[] } { return !!value && typeof value === 'object' && typeof (value as { key?: unknown }).key === 'string' && Array.isArray((value as { rolls?: unknown }).rolls) }
function isModifier(value: unknown): value is { characterId: string; featureId: string; featureLabel: string; modifierKind?: string; additionalDice?: number; dieSides?: number; direction?: string } { return !!value && typeof value === 'object' && typeof (value as { characterId?: unknown }).characterId === 'string' && typeof (value as { featureId?: unknown }).featureId === 'string' && typeof (value as { featureLabel?: unknown }).featureLabel === 'string' }
function interruptDescription(interrupt: MobileInterruptView) { const payload = interrupt.payload; if (interrupt.kind === 'plugin-choice') return String(payload.prompt || '请选择一项。'); if (interrupt.kind === 'roll-confirmation') return `${String(payload.targetName || '')} 的${String(payload.label || 'd20 投掷')}结果为 ${String(payload.originalValue || '—')}。`; return String(payload.description ?? payload.prompt ?? payload.reason ?? '请决定是否使用本次反应或特性。') }

const styles = StyleSheet.create({ banner: { position: 'absolute', left: 9, right: 9, top: 7, zIndex: 50, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#1b1522f8', borderColor: colors.warning, borderWidth: 1, borderRadius: 15, padding: 11 }, pulse: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.warning }, eyebrow: { color: colors.warning, fontSize: 8, fontWeight: '900' }, title: { color: colors.text, fontWeight: '900', marginTop: 2 }, meta: { color: colors.muted, fontSize: 8, marginTop: 2 }, open: { color: '#fff', backgroundColor: colors.primary, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 9, overflow: 'hidden', fontSize: 9, fontWeight: '900' }, backdrop: { flex: 1, justifyContent: 'center', padding: 16, backgroundColor: '#000b' }, dialog: { maxHeight: '82%', borderWidth: 1, borderColor: colors.warning, borderRadius: 20, backgroundColor: colors.background, padding: 15 }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, dialogEyebrow: { color: colors.warning, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, dialogTitle: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 3 }, close: { color: colors.muted, fontSize: 27 }, description: { color: '#d8d4e3', fontSize: 11, lineHeight: 18, marginTop: 10 }, scroll: { marginTop: 12 }, options: { gap: 8, paddingBottom: 4 }, choice: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 12, padding: 11 }, choicePrimary: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, choiceLabel: { color: colors.text, fontSize: 11, fontWeight: '900' }, choiceDetail: { color: colors.muted, fontSize: 9, lineHeight: 14, marginTop: 3 }, two: { flexDirection: 'row', gap: 8 }, optionGroup: { gap: 8 }, modifier: { gap: 6 }, replacement: { color: colors.text, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 9, backgroundColor: colors.surface }, hint: { color: colors.muted, fontSize: 10, lineHeight: 17 }, diceGroup: { borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 10 }, diceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 8 }, die: { width: 42, height: 42, borderRadius: 10, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, dieActive: { borderColor: colors.danger, backgroundColor: '#34131d' }, dieText: { color: colors.text, fontWeight: '900' }, roll: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: colors.primary, backgroundColor: colors.primarySoft, borderRadius: 12, padding: 11 }, rollLabel: { color: colors.text, fontWeight: '800' }, rollValue: { color: '#d8ccff', fontSize: 24, fontWeight: '900' }, unsupported: { color: colors.warning, fontSize: 10, lineHeight: 17 }, disabled: { opacity: .35 } })
