import { expect, test } from '@playwright/test'
for (const mixed of [false,true]) test(`concurrent player checks remain FIFO, mixed=${mixed}`, async ({context,page:dm}) => {
 test.setTimeout(90000)
 const player1=await context.newPage(), player2=await context.newPage()
 await dm.goto('http://127.0.0.1:6373/e2e/fixtures/concurrent-checks.html')
 await player1.goto('http://127.0.0.1:6373/e2e/fixtures/concurrent-checks.html?player=1')
 await player2.goto('http://127.0.0.1:6373/e2e/fixtures/concurrent-checks.html?player=2')
 await dm.evaluate(()=>{(window as unknown as {results:unknown[]}).results=[];window.addEventListener('message',e=>{if(e.data?.type==='dice-box-roll-result')(window as unknown as {results:unknown[]}).results.push(e.data)})})
 await player1.getByRole('button',{name:'投掷鉴定',exact:true}).click()
 await expect(dm.getByTestId('active')).toHaveText('player-1-single')
 await player2.getByRole('button',{name:mixed?'双 D20 鉴定':'投掷鉴定',exact:true}).click()
 await expect(dm.getByTestId('active')).toHaveText('player-1-single')
 const order=['player-1-single',`player-2-${mixed?'pair':'single'}`]
 await expect(dm.getByTestId('received')).toHaveText(JSON.stringify(order))
 await expect(dm.getByTestId('physical')).toHaveText(JSON.stringify(order),{timeout:45000})
 await expect(dm.getByTestId('finished')).toHaveText(JSON.stringify(order))
 const results=await dm.evaluate(()=>(window as unknown as {results:Array<{values:number[];fallback?:boolean}>}).results)
 expect(results.map(result=>result.values)).toEqual([[15],mixed?[4,18]:[7]])
 expect(results.some(result=>result.fallback)).toBe(false)
 await Promise.all([player1.close(),player2.close()])
})

test('waiting for DM confirmation does not consume the next player animation timeout', async ({context,page:dm}) => {
 test.setTimeout(90000)
 const p1=await context.newPage(),p2=await context.newPage()
 await dm.goto('http://127.0.0.1:6373/e2e/fixtures/concurrent-checks.html?hold')
 await p1.goto('http://127.0.0.1:6373/e2e/fixtures/concurrent-checks.html?player=1')
 await p2.goto('http://127.0.0.1:6373/e2e/fixtures/concurrent-checks.html?player=2')
 await p1.getByRole('button',{name:'投掷鉴定',exact:true}).click()
 await expect(dm.getByTestId('active')).toHaveText('player-1-single')
 await p2.getByRole('button',{name:'投掷鉴定',exact:true}).click()
 await expect(dm.getByRole('button',{name:'确认第一名玩家',exact:true})).toBeVisible({timeout:15000})
 // Deliberately exceed the active-roll failsafe while the second roll is queued.
 await dm.waitForTimeout(12000)
 await expect(dm.getByTestId('physical')).toHaveText('["player-1-single"]')
 await expect(dm.getByTestId('finished')).toHaveText('["player-1-single"]')
 await dm.getByRole('button',{name:'确认第一名玩家',exact:true}).click()
 await expect(dm.getByTestId('physical')).toHaveText('["player-1-single","player-2-single"]',{timeout:20000})
 await expect(dm.getByTestId('finished')).toHaveText('["player-1-single","player-2-single"]')
 await Promise.all([p1.close(),p2.close()])
})
