import { expect, test } from '@playwright/test'
function pdfFixture() {
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R 4 0 R 5 0 R] /Count 3 >>', ...[6, 7, 8].map((stream, i) => `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 ${i === 1 ? 400 : 600}] /Resources << /Font << /F1 9 0 R >> >> /Contents ${stream} 0 R >>`), ...['Welcome to castle', 'Silver key in cellar', 'Secret dragon chamber'].map(text => { const content = `BT /F1 24 Tf 30 320 Td (${text}) Tj ET`; return `<< /Length ${content.length} >>\nstream\n${content}\nendstream` }), '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']
  let text = '%PDF-1.4\n'; const offsets = [0]
  objects.forEach((obj, index) => { offsets.push(Buffer.byteLength(text)); text += `${index + 1} 0 obj\n${obj}\nendobj\n` })
  const offset = Buffer.byteLength(text)
  text += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map(n => `${String(n).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${offset}\n%%EOF`
  return Buffer.from(text)
}
test('reading, search, resize, minimize, restore and clipped export', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:6383/e2e/fixtures/pdf-reader.html', { waitUntil: 'commit' })
  await page.locator('input[type=file]').setInputFiles({ name: 'reader-test.pdf', mimeType: 'application/pdf', buffer: pdfFixture() })
  await expect(page.locator('[data-pdf-continuous-page="1"]')).toHaveAttribute('data-rendered', 'true')
  await page.getByRole('button', { name: '搜索', exact: true }).click()
  await page.getByLabel('搜索 PDF 全文').fill('Silver key')
  await page.getByRole('button', { name: '查找', exact: true }).click()
  await expect(page.getByLabel('匹配页计数')).toHaveText('1/1')
  await expect(page.getByRole('button', { name: /Silver key in cellar/ })).toHaveCount(0)
  await page.getByRole('button', { name: '下一个匹配页', exact: true }).click()
  await page.getByLabel('关闭导航').click()
  await expect(page.getByLabel('印刷页码，回车跳转')).toHaveValue('2')
  await expect(page.locator('[data-pdf-continuous-page="2"]')).toHaveAttribute('data-rendered', 'true')
  await page.getByLabel('放大 PDF').click()
  await expect(page.getByTestId('pdf-continuous-document-renderer')).toHaveAttribute('data-zoom-percent', '125')
  await page.getByRole('button', { name: '收藏', exact: true }).click()
  await page.getByRole('button', { name: '收藏当前页', exact: true }).click()
  await page.getByLabel('印刷页码偏移').fill('1')
  await page.getByLabel('关闭导航').click()
  const pdfPage = page.locator('[data-pdf-continuous-page="2"]')
  const beforeResize = await pdfPage.evaluate(element => element.getBoundingClientRect().width)
  const separator = page.getByRole('separator')
  const edge = await separator.boundingBox()
  await page.mouse.move(edge!.x + edge!.width / 2, edge!.y + 250)
  await page.mouse.down(); await page.mouse.move(edge!.x - 100, edge!.y + 250, { steps: 10 }); await page.mouse.up()
  await expect.poll(() => pdfPage.evaluate(element => element.getBoundingClientRect().width)).toBe(beforeResize)
  await page.getByTitle('适合宽度', { exact: true }).click()
  await expect.poll(() => pdfPage.evaluate(element => element.getBoundingClientRect().width)).toBeLessThan(beforeResize)
  await page.getByLabel('放大 PDF').click()
  await separator.focus(); await page.keyboard.press('ArrowRight')
  await page.getByLabel('收起资料区').click()
  await expect(page.getByTestId('pdf-split-view-panel')).toBeHidden()
  await page.getByLabel('展开资料区').click()
  await expect(page.getByLabel('印刷页码，回车跳转')).toHaveValue('1')
  await page.reload({ waitUntil: 'commit' })
  await expect(page.getByTestId('pdf-continuous-document-renderer')).toHaveAttribute('data-zoom-percent', '125')
  await expect(page.getByLabel('印刷页码，回车跳转')).toHaveValue('1')
  await expect(page.locator('[data-pdf-continuous-page="2"]')).toHaveAttribute('data-rendered', 'true')
  await page.screenshot({ path: 'test-results/pdf-reader-preview.png' })
  const result = await page.evaluate(() => (window as unknown as { testCrop: () => Promise<unknown> }).testCrop())
  expect(result).toEqual({ width: 200, height: 300, pixel: [0, 0, 255, 255] })
  expect(errors).toEqual([])
})
