import { dnd5eSpellActionIcon, type Dnd5eActionIconSpec } from '../../lib/dnd5eActionIcons'
import type { MapSpellStatusId } from './tokenStatusTooltip'

export const MAP_SPELL_STATUS_ICONS: Readonly<Record<MapSpellStatusId, Dnd5eActionIconSpec>> = {
  guidance: dnd5eSpellActionIcon({
    id: 'guidance',
    name: '神导术',
    englishName: 'Guidance',
    school: '预言',
    effect: '神圣增益',
  }),
  resistance: dnd5eSpellActionIcon({
    id: 'resistance',
    name: '提升抗性',
    englishName: 'Resistance',
    school: '防护',
    effect: '防护增益',
  }),
  sanctuary: dnd5eSpellActionIcon({
    id: 'sanctuary',
    name: '庇护术',
    englishName: 'Sanctuary',
    school: '防护',
    effect: '神圣防护',
  }),
  bless: dnd5eSpellActionIcon({
    id: 'bless',
    name: '祝福术',
    englishName: 'Bless',
    school: '附魔',
    effect: '神圣增益',
  }),
  bane: dnd5eSpellActionIcon({
    id: 'bane',
    name: '灾祸术',
    englishName: 'Bane',
    school: '附魔',
    effect: '诅咒减益',
  }),
  'shield-of-faith': dnd5eSpellActionIcon({
    id: 'shield-of-faith',
    name: '虔诚护盾',
    englishName: 'Shield of Faith',
    school: '防护',
    effect: '神圣防护',
  }),
  'mage-armor': dnd5eSpellActionIcon({
    id: 'mage-armor',
    name: '法师护甲',
    englishName: 'Mage Armor',
    school: '防护',
    effect: '奥术防护',
  }),
  jump: dnd5eSpellActionIcon({
    id: 'jump',
    name: '跳跃术',
    englishName: 'Jump',
    school: '变化',
    effect: '跃动强化',
  }),
  darkvision: dnd5eSpellActionIcon({
    id: 'darkvision',
    name: '黑暗视觉',
    englishName: 'Darkvision',
    school: '变化',
    effect: '夜视感知',
  }),
  'see-invisibility': dnd5eSpellActionIcon({
    id: 'see-invisibility',
    name: '识破隐形',
    englishName: 'See Invisibility',
    school: '预言',
    effect: '真实视野',
  }),
  'warding-bond': dnd5eSpellActionIcon({
    id: 'warding-bond',
    name: '守护之链',
    englishName: 'Warding Bond',
    school: '防护',
    effect: '守护联结',
  }),
  fly: dnd5eSpellActionIcon({
    id: 'fly',
    name: '飞行术',
    englishName: 'Fly',
    school: '变化',
    effect: '飞行强化',
  }),
  heroism: dnd5eSpellActionIcon({
    id: 'heroism',
    name: '英雄气概',
    englishName: 'Heroism',
    school: '附魔',
    effect: '勇气增益',
  }),
  'enlarge-reduce': dnd5eSpellActionIcon({
    id: 'enlarge-reduce',
    name: '变巨/缩小术',
    englishName: 'Enlarge/Reduce',
    school: '变化',
    effect: '体型变化',
  }),
  'enhance-ability': dnd5eSpellActionIcon({
    id: 'enhance-ability',
    name: '强化属性',
    englishName: 'Enhance Ability',
    school: '变化',
    effect: '属性强化',
  }),
  'divine-favor': dnd5eSpellActionIcon({
    id: 'divine-favor',
    name: '神恩',
    englishName: 'Divine Favor',
    school: '塑能',
    effect: '神圣武器强化',
  }),
  'hunters-mark': dnd5eSpellActionIcon({
    id: 'hunters-mark',
    name: '猎人印记',
    englishName: "Hunter's Mark",
    school: '预言',
    effect: '猎杀标记',
  }),
  'magic-weapon': dnd5eSpellActionIcon({
    id: 'magic-weapon',
    name: '魔化武器',
    englishName: 'Magic Weapon',
    school: '变化',
    effect: '魔法武器强化',
  }),
  'flame-blade': dnd5eSpellActionIcon({
    id: 'flame-blade',
    name: '火焰刀',
    englishName: 'Flame Blade',
    school: '塑能',
    effect: '燃烧刀刃',
  }),
  invisibility: dnd5eSpellActionIcon({
    id: 'invisibility',
    name: '隐形术',
    englishName: 'Invisibility',
    school: '幻术',
    effect: '隐匿身形',
  }),
  blur: dnd5eSpellActionIcon({
    id: 'blur',
    name: '朦胧术',
    englishName: 'Blur',
    school: '幻术',
    effect: '扭曲身影',
  }),
  barkskin: dnd5eSpellActionIcon({
    id: 'barkskin',
    name: '树肤术',
    englishName: 'Barkskin',
    school: '变化',
    effect: '树皮护甲',
  }),
  'protection-from-poison': dnd5eSpellActionIcon({
    id: 'protection-from-poison',
    name: '防护毒素',
    englishName: 'Protection from Poison',
    school: '防护',
    effect: '毒素防护',
  }),
  longstrider: dnd5eSpellActionIcon({
    id: 'longstrider',
    name: '大步奔行',
    englishName: 'Longstrider',
    school: '变化',
    effect: '移动强化',
  }),
  'protection-from-energy': dnd5eSpellActionIcon({
    id: 'protection-from-energy',
    name: '防护能量伤害',
    englishName: 'Protection from Energy',
    school: '防护',
    effect: '能量抗性',
  }),
  'death-ward': dnd5eSpellActionIcon({
    id: 'death-ward',
    name: '防死结界',
    englishName: 'Death Ward',
    school: '防护',
    effect: '死亡防护',
  }),
  'greater-invisibility': dnd5eSpellActionIcon({
    id: 'greater-invisibility',
    name: '高等隐形术',
    englishName: 'Greater Invisibility',
    school: '幻术',
    effect: '高等隐匿',
  }),
  'charm-person': dnd5eSpellActionIcon({
    id: 'charm-person',
    name: '魅惑人类',
    englishName: 'Charm Person',
    school: '附魔',
    effect: '魅惑控制',
  }),
  'hideous-laughter': dnd5eSpellActionIcon({
    id: 'hideous-laughter',
    name: '狂笑术',
    englishName: 'Hideous Laughter',
    school: '附魔',
    effect: '失能狂笑',
  }),
  'hold-person': dnd5eSpellActionIcon({
    id: 'hold-person',
    name: '定身术',
    englishName: 'Hold Person',
    school: '附魔',
    effect: '麻痹定身',
  }),
  'blindness-deafness': dnd5eSpellActionIcon({
    id: 'blindness-deafness',
    name: '目盲/耳聋术',
    englishName: 'Blindness/Deafness',
    school: '死灵',
    effect: '感官剥夺',
  }),
  'monster-damage-aversion': {
    key: 'monster-damage-aversion',
    motif: 'fire',
    background: '#7c2d12',
    backgroundDeep: '#1c0703',
    accent: '#fb923c',
    glow: '#f97316',
    runeIndex: 0,
    textureRotation: 0,
    asset: '/assets/icons/flesh-golem-fire-aversion-status.png',
    assetMode: 'foreground',
  },
}
