// Generated by scripts/generate-srd-magic-item-rules.py from context-reviewed translations.
// Source: Wizards of the Coast SRD 5.1, CC BY 4.0. Do not hand-edit.

import type { Dnd5eSrdMagicItemRuleTextZh } from './magicItemRulesZh.generated'

export const DND5E_SRD_MAGIC_ITEM_RULES_ZH_REVIEWED:
  Readonly<Partial<Record<string, Dnd5eSrdMagicItemRuleTextZh>>> = {
  "amulet-of-the-planes": {
    "rulesText": "佩戴此护符时，你可以使用一个动作，说出另一个存在位面上一处你熟悉的地点，然后进行一次 DC 15 智力检定。检定成功时，你通过护符施展异界传送。检定失败时，你、距你 15 尺内的每个生物和每件物件都会前往一个随机目的地。掷 d100：结果为 1–60 时，你们前往你所指定位面上的一个随机地点；结果为 61–100 时，你们前往一个随机决定的存在位面。",
    "sourcePage": 207
  },
  "boots-of-levitation": {
    "rulesText": "穿着这双靴子时，你可以随意使用一个动作，对自己施展浮空术。",
    "sourcePage": 212
  },
  "eyes-of-charming": {
    "rulesText": "这副水晶镜片覆在双眼上，共有 3 点充能。佩戴镜片时，你可以使用一个动作并消耗 1 点充能，对你周围 30 尺内的一个类人生物施展魅惑人类（豁免 DC 13），但你和目标必须能看见彼此。镜片每天黎明时恢复所有已消耗的充能。",
    "sourcePage": 220
  },
  "ring-of-feather-falling": {
    "rulesText": "佩戴此戒指时，如果你坠落，你会以每轮 60 尺的速度下降，并且不会因坠落受到伤害。",
    "sourcePage": 236
  },
  "wand-of-magic-missiles": {
    "rulesText": "此魔杖共有 7 点充能。握持魔杖时，你可以使用一个动作并消耗 1 点或更多充能，通过魔杖施展魔法飞弹。消耗 1 点充能时，你施展该法术的 1 环版本；每额外消耗 1 点充能，施展所用法术位的环阶便提高一环。\n\n魔杖每天黎明时恢复 1d6 + 1 点已消耗的充能。如果你消耗了魔杖的最后 1 点充能，掷一次 d20；结果为 1 时，魔杖碎成灰烬并被摧毁。",
    "sourcePage": 249
  }
}
